name: Build mAT_GUI for Windows
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pyinstaller pillow pytesseract
      - name: Build .exe
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico --name mAT_GUI materialscanner_gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mAT_GUI.exe
          path: dist/mAT_GUI.exe
